name: fordev
description: Enquetes para programadores.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http:
  provider:
  equatable:
  get:
  flutter_secure_storage:
  localstorage:
  carousel_slider:
  intl:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 
  test:
  mockito: ^5.0.0
  faker: 
  flutter_lints: ^1.0.0



flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/

flutter_icons:
  ios: true
  android: true
  image_path_android: lib/ui/assets/icon/android.png
  image_path_ios: lib/ui/assets/icon/ios.png
  adaptive_icon_background: lib/ui/assets/icon/background.png
  adaptive_icon_foregroung: lib/ui/assets/icon/foreground.png
  